name: 'Duplicati Action'
author: 'Peter Evans'
description: 'A GitHub action for Duplicati - Store securely encrypted backups in the cloud!'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'  
  color: 'yellow'
